all: compile

compile: 
	ant -buildfile build.xml all

run: 
	ant -buildfile build.xml run

debug:
	ant -buildfile build.xml run -Darg0=input_folder/input-1.txt -Darg1=output_folder/outpu1.txt -Darg2=1
